create table if not exists public.print_jobs (
  id bigint generated by default as identity primary key,
  launch_id bigint,
  product_name text not null,
  category text,
  storage text,
  launched_at timestamptz,
  expires_at timestamptz,
  user_name text,
  tspl text not null,
  status text not null default 'pending',
  error_message text,
  printer_name text,
  created_at timestamptz not null default now(),
  printed_at timestamptz
);

create index if not exists print_jobs_status_created_at_idx
  on public.print_jobs (status, created_at);
